version: '3'

services:
  db:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
     #- ./mysql-data:/var/lib/mysql
      - ./mysql-scripts:/mysql-scripts
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_USER}



