CREATE TABLE Users (
	IdUser INT NOT NULL AUTO_INCREMENT,
	Username VARCHAR(255) NOT NULL,
    PRIMARY KEY (IdUser)
);

CREATE TABLE Images (
    IdImage INT NOT NULL AUTO_INCREMENT,
    Path VARCHAR(255) NOT NULL,
    PRIMARY KEY (IdImage)
);

CREATE TABLE Points (
	IdPoint INT NOT NULL AUTO_INCREMENT,
    XCoord INT NOT NULL,
    YCoord INT NOT NULL,
    IdUser INT NOT NULL,
    IdImage INT NOT NULL,
    PRIMARY KEY (IdPoint),
    FOREIGN KEY (IdUser) REFERENCES Users(IdUser),
    FOREIGN KEY (IdImage) REFERENCES Images(IdImage)
);